services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
      POSTGRES_DB: demo
    networks:
      - db-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d demo -U demo" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    container_name: migrate
    image: migrate/migrate
    networks:
      - db-net
    volumes:
      - ./migrations:/migrations/
    command: [
      "-path",
      "/migrations",
      "-database",
      "postgres://demo:demo@db:5432/demo?sslmode=disable",
      "up"
    ]

    depends_on:
      db:
          condition: service_healthy
    links:
      - db

  nats:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - db-net
    restart: always
    command: [
      "-p",
      "4222",
      "-hbi",
      "5s",
      "-hbt",
      "5s",
      "-hbf",
      "2",
      "-SD",
      "-cid",
      "demo-cluster",
      "-m",
      "8222"
    ]

networks:
  db-net: